# Generated by Django 4.2 on 2024-08-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последнего обновления'),
        ),
    ]
